ALTER TABLE player_cache
    ADD COLUMN IF NOT EXISTS player_name VARCHAR(128) NULL;

ALTER TABLE player_cache
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45) NULL;

ALTER TABLE player_cache
    ADD COLUMN IF NOT EXISTS gokz_rating NUMERIC(10,2) NULL;
