ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS steam_id_3 VARCHAR(64);

ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS steam_id_64 VARCHAR(64);

ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS remark TEXT;
